version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "maintainer"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  alembic:
    build: 
      context: .
      dockerfile: src/alembic/Dockerfile
    command: alembic upgrade head
    ports:
      - "80:80"
    working_dir: /app/src   
    volumes:
      - .:/app
    depends_on:
      - db

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow

  web:
    container_name: web
    build: .
    working_dir: /app/src 
    ports:
      - "90:90"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "90"]

  tests:
    container_name: tests
    build: .
    working_dir: /app/src
    volumes:
      - .:/app
    command: ["pytest","-v", "tests.py"]
    depends_on:
      - db
      - alembic

volumes:
  postgres_data: