version: '3.8'

services:
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_USER:
  #     POSTGRES_PASSWORD:
  #     POSTGRES_DB:
  #   ports:
  #     - ""
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

  # alembic:
  #   build: .
  #   command: alembic upgrade head
  #   volumes:
  #     - .:/code
    # depends_on:
    #   - db
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow

# volumes:
#   postgres_data:
